---
title: "hcrpaper"
author: "Rosalind Pan"
date: "10 May 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Figure S1A

```{r}
scer_fclist100 <- read.table("/Users/rosalindpan/drummondlab/hcrpaper/data/fcr_distribution/scer_fclist100.txt")
scer_fclist50 <- read.table("/Users/rosalindpan/drummondlab/hcrpaper/data/fcr_distribution/scer_fclist50.txt")
scernull_fclist <- read.table("/Users/rosalindpan/drummondlab/hcrpaper/data/fcr_distribution/scernull_fclist.txt")
```

```{r}
d_100 <- density(scer_fclist100$V1, kernel = "rectangular")
plot(d_100, main = "Rectangular kernel", col='#828282',
     xlim=c(0,1))
```


```{r}
d_100 <- density(scer_fclist100$V1, kernel = "rectangular")
d_50 <- density(scer_fclist50$V1, kernel = "rectangular")
d_null <- density(scernull_fclist$V1, kernel = "rectangular")

plot(d_100, main = "Rectangular kernel", col='#828282',
     xlim=c(0,1), ylim=c(0,2.5))
lines(d_50, main = "Rectangular kernel")
lines(d_null, main = "Rectangular kernel", col='#AA4499')
legend(x = "topleft", legend=c('hits', 'rand', 'IDR'),
       lty = c(1, 1, 1),
       col = c('#828282', 'black', '#AA4499'))
```





```{r}
hits_aq <- read.csv("D:/research/drummond-lab/data/aln_quality_hits.csv")
rand_aq <- read.csv("D:/research/drummond-lab/data/aln_quality_random.csv")
idr_aq <- read.csv("D:/research/drummond-lab/data/aln_quality_disprot.csv")
```

```{r}
d_hits <- density(hits_aq$gappiness,
             kernel = "rectangular")
d_idr <- density(idr_aq$gappiness,
             kernel = "rectangular")
d_rand <- density(hits_aq$gappiness_null,
             kernel = "rectangular")
d_rand2 <- density(rand_aq$gappiness,
             kernel = "rectangular")


plot(d_hits, main = "Rectangular kernel", col='#AA4499',
     xlim=c(0,1), ylim=c(0,3.5))
lines(d_idr, main = "Rectangular kernel", col='#828282')
lines(d_rand, main = "Rectangular kernel", col='black')
lines(d_rand2, main = "Rectangular kernel", col='black', lty='dotted')
legend(x = "topright", legend=c('hits', 'IDR', 'rand', 'rand2'),
       lty = c(1, 1, 1, 4),
       col = c('#AA4499', '#828282', 'black', 'black'))
```

```{r, fig.width=5, fig.height=5}
d_hits <- density(hits_aq$seq_div,
             kernel = "rectangular")
d_idr <- density(idr_aq$seq_div,
             kernel = "rectangular")
d_rand <- density(hits_aq$seq_div_null,
             kernel = "rectangular")
d_rand2 <- density(rand_aq$seq_div,
             kernel = "rectangular")


plot(d_hits, main = "Rectangular kernel", col='#AA4499',
     xlim=c(0,2), ylim=c(0,3.5))
lines(d_idr, main = "Rectangular kernel", col='#828282')
lines(d_rand, main = "Rectangular kernel", col='black')
lines(d_rand2, main = "Rectangular kernel", col='black', lty='dotted')
legend(x = "topright", legend=c('hits', 'IDR', 'rand', 'rand2'),
       lty = c(1, 1, 1, 4),
       col = c('#AA4499', '#828282', 'black', 'black'))
```